server.port=8080

# URL donde estará levantado el Backend original (ahora puramente motor de base de datos y lógica)
backend.api.url=http://localhost:8081

# Clave interna compartida con la API para autenticar las llamadas inter-servicio
internal.api.key=ClmmInternalSecretKey2026_NoCompartir

# Configuración JWT [MIDDLEWARE - SEGURIDAD]
# Debe tener al menos 32 caracteres para cumplir los 256 bits
jwt.secret=EstaEsUnaClaveSecretaMuyLargaYSeguraParaElProyecto2026
jwt.expiration.ms=3600000
jwt.renewal.ms=600000

# Configuracion Mail de Google para mandar correos [MIDDLEWARE - NOTIFICACIONES]
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=clmm.prfinaldam@gmail.com
spring.mail.password=oaiz iiqe thom mszt
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

# URL del frontend para CORS
app.frontend.url=http://localhost:4200

# Puerto para WebSockets del Lobby y Juego (Unificado)
socketio.port=8082
