#Configuracion MySQL [BACK / DATOS]
spring.datasource.url=jdbc:mysql://localhost:3306/prueba_prfinal?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=JeG7BUOh-
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Clave interna: debe ser IDENTICA a la del Middleware
internal.api.key=ClmmInternalSecretKey2026_NoCompartir

# Configuracion MongoDB [ESTADISTICAS]
spring.mongodb.uri=${SPRING_DATA_MONGODB_URI:mongodb://localhost:27017/batalla_naval_stats}
spring.mongodb.database=batalla_naval_stats

server.port=8081
